name: auto-build

on:
  push:
    branches: master

jobs:
  build:
    strategy:
      matrix:
        python-version: [ "3.6", "3.7", "3.8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pip Install
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
            name: 17wanxiaoCheckin-CF.py${{ matrix.python-version }}
            path: ./